import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts"
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Session } from "inspector";
import ServiceWorkerWrapper from "./lib/hooks/useServiceWorker";

export const metadata: Metadata = {
  title: "H4 Team Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

//   useEffect(() => {
//     if("serviceWorker" in navigator) {
//         navigator.serviceWorker.register("/sw.js")
//             .then((registration: ServiceWorkerRegistration) => {
//                 console.log("service worker registered with scope:", registration.scope)
//             })
//             .catch((error: Error) => {
//                 console.error("service worker registration failed: ", error)
//             })
//     }
// }, [])
  
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          {children}
          <ServiceWorkerWrapper />
        </body>
      </html>
    </SessionProvider>
  );
}
